# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='input_files')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
