# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180726_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='input_files/'),
        ),
    ]
